import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ENTRY_PATTERN =
  /^##\s+([0-9]+\.[0-9]+\.[0-9]+)\s+—\s+([0-9]{4}-[0-9]{2}-[0-9]{2})\n([\s\S]*?)(?=^##\s+|\s*$)/gm;

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export const repoRoot = path.resolve(__dirname, '../..');

export const paths = {
  version: path.join(repoRoot, 'version.json'),
  changelog: path.join(repoRoot, 'CHANGELOG.md'),
  packageJson: path.join(repoRoot, 'package.json'),
  packageLock: path.join(repoRoot, 'package-lock.json'),
  versioningDoc: path.join(repoRoot, 'docs', 'versioning.md'),
};

export function normaliseNewlines(value) {
  return value.replace(/\r\n/g, '\n').replace(/\uFEFF/g, '');
}

export function readText(filePath) {
  return normaliseNewlines(readFileSync(filePath, 'utf8'));
}

export function writeText(filePath, content) {
  const next = content.endsWith('\n') ? content : `${content}\n`;
  writeFileSync(filePath, next, 'utf8');
}

export function readJson(filePath) {
  return JSON.parse(readText(filePath));
}

export function writeJson(filePath, value) {
  writeText(filePath, `${JSON.stringify(value, null, 2)}\n`);
}

export function normaliseChangelog(raw, versionMeta) {
  const stripped = normaliseNewlines(raw)
    .replace(/^# NexusOS Changelog\s*$/gm, '')
    .trim();

  const entries = [...stripped.matchAll(ENTRY_PATTERN)];
  if (entries.length === 0) {
    throw new Error('CHANGELOG.md does not contain any release entries.');
  }

  const body = entries
    .map((match) => {
      const version = match[1];
      const date = version === versionMeta.version ? versionMeta.date : match[2];
      const notes = match[3].trim().replace(/\n{3,}/g, '\n\n');
      return `## ${version} — ${date}\n${notes}`;
    })
    .join('\n\n');

  return `# NexusOS Changelog\n\n${body}\n`;
}

export function readLatestChangelogEntry(changelogText) {
  const entries = [...normaliseNewlines(changelogText).matchAll(ENTRY_PATTERN)];
  if (entries.length === 0) {
    throw new Error('CHANGELOG.md does not contain a latest release entry.');
  }

  const [first] = entries;
  const notes = first[3]
    .trim()
    .split('\n')
    .map((line) => line.trimRight())
    .filter(Boolean);

  return {
    version: first[1],
    date: first[2],
    notes,
  };
}

export function renderVersioningDoc(versionMeta, latestEntry) {
  const noteLines = latestEntry.notes.map((line) => (line.startsWith('- ') ? line : `- ${line}`));

  return `# NexusOS Versioning

> Auto-generated by \`npm run version:sync\`. Do not edit manually.

## Current Release
- Version: \`${versionMeta.version}\`
- Build: \`${versionMeta.build}\`
- Full label: \`${versionMeta.full}\`
- Release date: \`${versionMeta.date}\`

## Latest Release Notes
${noteLines.join('\n')}

## Canonical Files
- [version.json](../version.json) is the canonical release metadata.
- [CHANGELOG.md](../CHANGELOG.md) stores release notes in descending order.
- [package.json](../package.json) and [package-lock.json](../package-lock.json) are synced automatically from \`version.json\`.
- [docs/versioning.md](./versioning.md) is regenerated automatically from the current release metadata and changelog.

## Automatic Enforcement
- \`npm run version:sync\` normalizes \`CHANGELOG.md\`, syncs package versions, and regenerates this document.
- \`npm run version:check\` fails when any versioning file drifts out of sync.
- \`npm install\` runs \`prepare\`, which configures Git to use the repo-managed hooks in \`.githooks/\`.
- \`.githooks/pre-commit\` runs the sync step and stages any updated versioning files.
- \`.githooks/pre-push\` runs the check step so version drift is blocked before push.
- \`.github/workflows/versioning.yml\` runs the same check in CI on pushes and pull requests.

## Release Workflow
1. Run \`./version-bump.ps1 patch|minor|major "release note"\`.
2. The bump script updates \`version.json\`, prepends the changelog entry, syncs the remaining version files, and commits the result.
3. Push normally. The local hook and CI workflow verify that the versioning files stayed aligned.
`;
}
