/**
 * Generates a copy-paste-ready invite message for new members.
 * Used in Key Management after issuing a key.
 */
import React, { useState } from 'react';
import { Copy, Check } from 'lucide-react';

export default function InviteMessageBuilder({ username, rank, authKey, appUrl }) {
  const [copied, setCopied] = useState(false);
  
  const baseUrl = appUrl || window.location.origin;
  
  const message = `🔴 REDSCAR NOMADS — NexusOS Access

Welcome to NexusOS, the Redscar Nomads operational coordination platform.

Your credentials:
━━━━━━━━━━━━━━━━━━━━
Username: ${(username || '').toUpperCase()}
Auth Key: ${authKey}
Rank: ${rank || 'SCOUT'}
━━━━━━━━━━━━━━━━━━━━

Login here: ${baseUrl}

Steps:
1. Open the link above
2. Enter your username and auth key exactly as shown
3. Complete the onboarding flow
4. Your callsign can be changed later in Settings

⚠️ IMPORTANT: Store your auth key securely. It cannot be recovered — only regenerated by a Pioneer.

See you in the verse. o7`;

  const handleCopy = () => {
    navigator.clipboard.writeText(message);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div style={{
      marginTop: 12, padding: '12px 14px',
      background: 'var(--bg2)', border: '0.5px solid var(--b1)',
      borderRadius: 2,
    }}>
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8 }}>
        <span style={{ color: 'var(--t2)', fontSize: 9, letterSpacing: '0.1em', textTransform: 'uppercase' }}>
          READY-TO-SEND INVITE MESSAGE
        </span>
        <button onClick={handleCopy} style={{
          display: 'flex', alignItems: 'center', gap: 4,
          padding: '4px 10px', background: 'transparent',
          border: `0.5px solid ${copied ? 'var(--live-b)' : 'var(--b2)'}`,
          borderRadius: 2, cursor: 'pointer',
          color: copied ? 'var(--live)' : 'var(--acc)',
          fontFamily: "'Barlow Condensed', sans-serif",
          fontSize: 9, letterSpacing: '0.08em',
        }}>
          {copied ? <Check size={10} /> : <Copy size={10} />}
          {copied ? 'COPIED' : 'COPY INVITE'}
        </button>
      </div>
      <pre style={{
        color: 'var(--t2)', fontSize: 10, lineHeight: 1.6,
        whiteSpace: 'pre-wrap', wordBreak: 'break-word',
        maxHeight: 200, overflow: 'auto',
        fontFamily: "'Barlow Condensed', sans-serif",
      }}>{message}</pre>
    </div>
  );
}