/**
 * tutorialSteps.js — Defines all guided tour steps and getting-started checklist items.
 * Each step targets a section of the app and provides contextual guidance.
 */

export const TOUR_STEPS = [
  {
    id: 'welcome',
    title: 'Welcome to NexusOS',
    body: 'This guided tour will walk you through the core modules of NexusOS — your org\'s operational command center. Each step highlights a key area and explains what it does. Use arrow keys or click Next to proceed.',
    detail: 'The tour takes about 2 minutes. You can skip at any time and replay it later from the help button or Settings.',
    icon: '🧭',
    route: null,
  },
  {
    id: 'sidebar',
    title: 'Navigation Sidebar',
    body: 'The sidebar is your primary navigation hub. Modules are grouped by function: Operations, Industry, Scout Intel, Armory, and Org. Admin tools only appear for Pioneer-rank members.',
    detail: 'Below the navigation you\'ll find the Quick Status widget showing refinery timers, next op countdown, and pending requisitions. The Getting Started checklist also lives here.',
    icon: '📋',
    route: null,
  },
  {
    id: 'topbar',
    title: 'Live Status Bar',
    body: 'The topbar provides at-a-glance org health: coffer balance, your personal wallet, active refinery batches, live ops count, and online member count. Every chip is clickable — it jumps you to the relevant module.',
    detail: 'The notification bell shows unread alerts from ops, scout intel, and system events. The user chip on the right opens your Settings.',
    icon: '📊',
    route: null,
  },
  {
    id: 'industry',
    title: 'Industry Hub',
    body: 'The central workspace for all industrial operations. Track raw materials in the ledger, manage blueprints and crafting queues, monitor refinery batches, and analyze production throughput.',
    detail: 'Key tabs: Overview (dashboard), Materials (ledger), Blueprints (registry), Craft Queue (active jobs), Refinery (batch tracking), Guide (full crafting reference with recipes), Prices (live commodity data), and 20+ more specialized views.',
    icon: '🏭',
    route: '/app/industry',
  },
  {
    id: 'industry_guide',
    title: 'Crafting Reference Guide',
    body: 'The Guide tab inside Industry Hub is your comprehensive crafting encyclopedia. It lists every known blueprint, required materials, quality thresholds, crafting times, and estimated market values.',
    detail: 'Use the search bar to find specific items. Filter by tier (T1/T2), category, or owned-by to quickly locate what you need. Material quality directly affects output stats via the quality multiplier.',
    icon: '📖',
    route: '/app/industry?tab=guide',
  },
  {
    id: 'ops',
    title: 'Ops Board',
    body: 'Plan, schedule, and run live operations with your crew. Create ops with named phases, role slots, and readiness gates. Once live, the command center provides real-time crew tracking, event logging, loot tallying, and financial split calculations.',
    detail: 'Key features: Op Creator (wizard-style builder), Timeline (calendar view with ICS export), Mission Planner (strategic planning), and Live Op (real-time command center with dual-layout support).',
    icon: '🎯',
    route: '/app/ops',
  },
  {
    id: 'ops_timeline',
    title: 'Ops Timeline & RSVP',
    body: 'The Timeline view shows upcoming operations on a visual calendar. Click any op to RSVP with your preferred role and ship. Leadership can assign crew to specific ship stations from the live op view.',
    detail: 'Export your schedule to your personal calendar using the ICS download. Ship availability tracking shows which org vessels are free for each time slot.',
    icon: '📅',
    route: '/app/ops/timeline',
  },
  {
    id: 'scout',
    title: 'Scout Intel',
    body: 'Log and share deposit discoveries across the org. The interactive system map visualizes all known deposits with quality-coded markers. High-quality finds (80%+) automatically notify org members.',
    detail: 'Three main views: Deposits (interactive map + log form), Live Map (real-time spatial overview with layer toggles), and Routes (mining circuit planner for optimized multi-stop runs).',
    icon: '🛰️',
    route: '/app/scout',
  },
  {
    id: 'market',
    title: 'Market Hub',
    body: 'Live commodity prices synced from UEX every 15 minutes via the automated Stanton Crawler. Track price trends, set custom alerts, browse trade routes ranked by profit/SCU, and analyze market volatility.',
    detail: 'Key tabs: Prices (sortable commodity table), Routes (profitable trade lanes), Analytics (trend charts, margin heatmaps, volatility tables), Marketplace (UEX player listings), Trade Board (org internal trades), and Price Watch (custom alert management).',
    icon: '📈',
    route: '/app/market',
  },
  {
    id: 'armory',
    title: 'Armory & Fleet',
    body: 'Manage the org\'s military and industrial assets. The Armory tracks equipment checkouts, the Fleet Hub manages ships with readiness scores and loadout configs, and the Asset Manager handles org-owned equipment.',
    detail: 'Sub-modules: Armory (equipment checkout/return), Fleet (ships, readiness, crew assignment), Assets (org property tracking with serial tags), Inventory (personal gear management with OCR scanning).',
    icon: '🛡️',
    route: '/app/armory',
  },
  {
    id: 'roster',
    title: 'Org Roster & Management',
    body: 'The Roster shows all org members with their rank, specialization, and last-seen status. Leadership can manage member details, adjust ranks, and track blueprint contributions from Member Management.',
    detail: 'Related tools: Debt Tracker (member balance management), Handbook (org rules and procedures), and Training Hub (skill development resources).',
    icon: '👥',
    route: '/app/roster',
  },
  {
    id: 'settings',
    title: 'Your Settings',
    body: 'Configure your NexusOS experience. Update your callsign (display name), choose between Alt-Tab and 2nd Monitor layout modes, enable browser notifications, manage your UEX API integration, and track your personal wallet.',
    detail: 'Your callsign can be changed anytime and updates everywhere instantly. Browser notifications alert you to live ops, high-value deposits, and distress calls even when NexusOS is in the background.',
    icon: '⚙️',
    route: '/app/settings',
  },
  {
    id: 'complete',
    title: 'Tour Complete — You\'re Ready!',
    body: 'You\'ve seen the major modules. Check the Getting Started checklist in the sidebar for recommended first actions — it tracks your progress as you explore.',
    detail: 'You can replay this tour anytime from the floating help button (bottom-right corner) or from the Settings page. The help button also shows page-specific tips wherever you are.',
    icon: '🎉',
    route: null,
  },
];

export const GETTING_STARTED_ITEMS = [
  {
    id: 'complete_tour',
    label: 'Complete the guided tour',
    description: 'Walk through each NexusOS module to understand the platform layout and capabilities.',
    icon: '🧭',
    category: 'SETUP',
  },
  {
    id: 'set_callsign',
    label: 'Set your callsign',
    description: 'Your callsign is your display name across the entire platform — it appears in ops, ledger entries, and the roster.',
    icon: '🏷️',
    route: '/app/settings',
    category: 'SETUP',
  },
  {
    id: 'set_layout',
    label: 'Choose your layout mode',
    description: 'Alt-Tab for single monitor gameplay, or 2nd Monitor for expanded live op command views on a secondary display.',
    icon: '🖥️',
    route: '/app/settings',
    category: 'SETUP',
  },
  {
    id: 'enable_notifications',
    label: 'Enable browser notifications',
    description: 'Get alerted when ops go live, high-value deposits are found, or distress calls come in — even with NexusOS minimized.',
    icon: '🔔',
    route: '/app/settings',
    category: 'SETUP',
  },
  {
    id: 'browse_industry',
    label: 'Browse the Industry Hub',
    description: 'Explore the materials ledger, blueprint registry, and crafting reference guide. Start on the Overview tab for the production dashboard.',
    icon: '🏭',
    route: '/app/industry',
    category: 'EXPLORE',
  },
  {
    id: 'read_guide',
    label: 'Read the Crafting Guide',
    description: 'The Guide tab in Industry Hub is your complete crafting encyclopedia — recipes, quality thresholds, and market values.',
    icon: '📖',
    route: '/app/industry?tab=guide',
    category: 'EXPLORE',
  },
  {
    id: 'check_ops',
    label: 'Check the Ops Board',
    description: 'See upcoming operations, their phases and role slots. RSVP to join one with your preferred role and ship.',
    icon: '🎯',
    route: '/app/ops',
    category: 'EXPLORE',
  },
  {
    id: 'check_market',
    label: 'Check live market prices',
    description: 'See what commodities are selling for across Stanton. Prices sync from UEX automatically every 15 minutes.',
    icon: '📈',
    route: '/app/market',
    category: 'EXPLORE',
  },
  {
    id: 'view_fleet',
    label: 'View the org fleet',
    description: 'See what ships are available, their cargo capacity, and readiness status. Leadership can assign ships to ops.',
    icon: '🚀',
    route: '/app/armory/fleet',
    category: 'EXPLORE',
  },
  {
    id: 'log_deposit',
    label: 'Log your first scout deposit',
    description: 'Found a good rock or salvage site? Log it with location and quality to share intel with the org.',
    icon: '🛰️',
    route: '/app/scout',
    category: 'CONTRIBUTE',
  },
  {
    id: 'log_material',
    label: 'Log a material to the ledger',
    description: 'Track salvage materials, ores, or crafting components you\'ve collected. Supports manual entry and OCR scanning.',
    icon: '📦',
    route: '/app/industry?tab=materials',
    category: 'CONTRIBUTE',
  },
  {
    id: 'read_handbook',
    label: 'Read the org handbook',
    description: 'Familiarize yourself with Redscar Nomads\' rules, rank structure, and operational procedures.',
    icon: '📕',
    route: '/app/handbook',
    category: 'EXPLORE',
  },
];

export const CATEGORIES = {
  SETUP: { label: 'Initial Setup', color: '#C8A84B' },
  EXPLORE: { label: 'Explore Modules', color: '#7AAECC' },
  CONTRIBUTE: { label: 'First Contributions', color: '#2edb7a' },
};