/**
 * tutorialSteps.js — Guided tour steps and getting-started checklist items
 * for the current Industry Hub / Market Hub release.
 */

export const TOUR_STEPS = [
  {
    id: 'welcome',
    title: 'Welcome to NexusOS',
    body: 'This release of NexusOS is intentionally narrowed to Industry Hub and Market Hub so mining, salvaging, crafting, inventory, and market intelligence can ship cleanly.',
    detail: 'The tour is short. You can skip it now and replay it later from the help button.',
    icon: '🧭',
    route: null,
  },
  {
    id: 'sidebar',
    title: 'Navigation Sidebar',
    body: 'The sidebar now exposes only the active release surfaces: Industry Hub, Inventory, and Market Hub.',
    detail: 'Everything else is hidden behind future-feature placeholders until the industry-first release is stable.',
    icon: '📋',
    route: null,
  },
  {
    id: 'topbar',
    title: 'Release Status Bar',
    body: 'The topbar keeps the current release centered on useful signals: org coffer, your wallet, refinery pressure, member presence, and Industry/Market notifications.',
    detail: 'Breadcrumbs follow the active Industry and Market views so navigation stays aligned with the underlying workflow.',
    icon: '📊',
    route: null,
  },
  {
    id: 'industry',
    title: 'Industry Hub',
    body: 'Industry Hub is the production command surface for mining, salvaging, refining, blueprint planning, crafting, and logistics.',
    detail: 'Tabs are grouped into Production, Market, and Logistics sections so you only expand the workflow you are actively using.',
    icon: '🏭',
    route: '/app/industry',
  },
  {
    id: 'materials',
    title: 'Materials Logging',
    body: 'Materials is the operational ledger for ores, salvage, refined output, and crafting inputs.',
    detail: 'Use it to log fresh haul data, review material quality, and decide whether to hold, refine, sell, or craft.',
    icon: '⛏️',
    route: '/app/industry?tab=materials',
  },
  {
    id: 'inventory_command',
    title: 'Inventory Command Center',
    body: 'Inventory inside Industry is the single source of truth for personal custody, org stock, shared gear, ship-linked assets, blueprint coverage, crafter lookup, and readiness.',
    detail: 'Switch between Holdings, Network, Assets, Gear, and Readiness using the inventory views rather than jumping between separate apps.',
    icon: '📦',
    route: '/app/industry?tab=inventory',
  },
  {
    id: 'crafting',
    title: 'Blueprints And Crafting',
    body: 'Guide, Blueprints, Craft Queue, and Production keep the crafting loop aligned from recipe discovery through queued work and output tracking.',
    detail: 'This is the live release path for turning mined or salvaged materials into planned production.',
    icon: '🧪',
    route: '/app/industry?tab=guide',
  },
  {
    id: 'market',
    title: 'Market Hub',
    body: 'Market Hub is the cached intelligence surface for commodity prices, routes, analytics, player listings, and internal trade decisions.',
    detail: 'UEX sync is throttled and cache-first, so the pages stay stable while still surfacing current route and pricing signals.',
    icon: '📈',
    route: '/app/market',
  },
  {
    id: 'complete',
    title: 'Tour Complete',
    body: 'You are now in the active release path. Use the checklist to move through the key logging, inventory, crafting, and market workflows.',
    detail: 'Future modules remain visible only as placeholders until the industry-first release is production-ready.',
    icon: '✅',
    route: null,
  },
];

export const GETTING_STARTED_ITEMS = [
  {
    id: 'complete_tour',
    label: 'Complete the guided tour',
    description: 'Walk through the current Industry Hub and Market Hub release surfaces.',
    icon: '🧭',
    category: 'SETUP',
  },
  {
    id: 'browse_industry',
    label: 'Open Industry Hub',
    description: 'Review the production dashboard and confirm the current release workflow layout.',
    icon: '🏭',
    route: '/app/industry',
    category: 'EXPLORE',
  },
  {
    id: 'log_material',
    label: 'Log a material record',
    description: 'Capture mined ore, salvage, or crafting stock in the materials ledger.',
    icon: '⛏️',
    route: '/app/industry?tab=materials',
    category: 'CONTRIBUTE',
  },
  {
    id: 'open_inventory_center',
    label: 'Open the inventory center',
    description: 'Review holdings, org stock, assets, shared gear, and craft readiness from one command surface.',
    icon: '📦',
    route: '/app/industry?tab=inventory',
    category: 'EXPLORE',
  },
  {
    id: 'review_refinery',
    label: 'Review refinery flow',
    description: 'Check active refinery work and confirm the refined-material pipeline.',
    icon: '🔥',
    route: '/app/industry?tab=refinery',
    category: 'EXPLORE',
  },
  {
    id: 'review_blueprints',
    label: 'Review the crafting guide',
    description: 'Use the guide to inspect blueprint requirements, quality thresholds, and output targets.',
    icon: '📖',
    route: '/app/industry?tab=guide',
    category: 'EXPLORE',
  },
  {
    id: 'queue_craft',
    label: 'Open the craft queue',
    description: 'Validate that materials, blueprint intent, and queue management stay aligned.',
    icon: '🛠️',
    route: '/app/industry?tab=craft',
    category: 'CONTRIBUTE',
  },
  {
    id: 'check_market',
    label: 'Open Market Hub',
    description: 'Review cached prices, route intelligence, and market signals for current material decisions.',
    icon: '📈',
    route: '/app/market',
    category: 'EXPLORE',
  },
  {
    id: 'review_routes',
    label: 'Review trade routes',
    description: 'Check cached route rankings before moving material or planning sell runs.',
    icon: '🛰️',
    route: '/app/market?tab=routes',
    category: 'EXPLORE',
  },
  {
    id: 'check_price_watch',
    label: 'Open price watch',
    description: 'Inspect the alert surface for threshold-based commodity monitoring.',
    icon: '🔔',
    route: '/app/market?tab=alerts',
    category: 'EXPLORE',
  },
];

export const CATEGORIES = {
  SETUP: { label: 'Release Setup', color: '#C8A84B' },
  EXPLORE: { label: 'Explore Surfaces', color: '#7AAECC' },
  CONTRIBUTE: { label: 'Log And Manage', color: '#2edb7a' },
};
